language: node_js
node_js:
  - '4.2'
  - '4.1'
  - '4.0'
  - node
before_install:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token: 30fa9fa8d7c319a275d455210239fe216b8fc9bee5e93221748e932b37642813